apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devops1
  template:
    metadata:
      labels:
        app: devops1
    spec:
      containers:
        - name: devops1
          image: jakubbyliniak/myapp:d1f600fbe4e96cd96ddc9fc313b6d16f70326825
          ports:
            - containerPort: 3000
          env:
            - name: APP_VERSION
              value: "v1.0.0"
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10